-- =====================================================
-- 기존 테이블 삭제 명령어 (MySQL/PostgreSQL 호환)
-- 외래키 의존성 순서에 따라 역순으로 삭제
-- =====================================================

-- 1. 외래키 제약조건 비활성화 (MySQL용)
-- SET FOREIGN_KEY_CHECKS = 0;

-- 2. PostgreSQL용 외래키 제약조건 임시 비활성화
-- SET session_replication_role = replica;

-- =====================================================
-- 테이블 삭제 (의존성 역순)
-- =====================================================

-- 최하위 의존성 테이블부터 삭제
DROP TABLE IF EXISTS "NaverPlaceKeywordRankHistories" CASCADE;
DROP TABLE IF EXISTS "KeywordRankHistories" CASCADE;
DROP TABLE IF EXISTS "AdKeywordRankHistories" CASCADE;
DROP TABLE IF EXISTS "Ads_Termination_Log" CASCADE;
DROP TABLE IF EXISTS "Ads_Payment" CASCADE;
DROP TABLE IF EXISTS "SumemPoints" CASCADE;
DROP TABLE IF EXISTS "PremiumPackages" CASCADE;
DROP TABLE IF EXISTS "Packages_Log" CASCADE;
DROP TABLE IF EXISTS "Packages" CASCADE;
DROP TABLE IF EXISTS "MarketingLead" CASCADE;
DROP TABLE IF EXISTS "App_Inquiry_Answer_AutoGenerated" CASCADE;
DROP TABLE IF EXISTS "App_Inquiry_Answer" CASCADE;
DROP TABLE IF EXISTS "App_Inquiry" CASCADE;
DROP TABLE IF EXISTS "AuthUsers_Card" CASCADE;
DROP TABLE IF EXISTS "Channels" CASCADE;
DROP TABLE IF EXISTS "Contracts" CASCADE;
DROP TABLE IF EXISTS "AdNaverPlaceKeywords" CASCADE;
DROP TABLE IF EXISTS "Ads_Keyword" CASCADE;
DROP TABLE IF EXISTS "AdKeywords" CASCADE;
DROP TABLE IF EXISTS "Ads" CASCADE;
DROP TABLE IF EXISTS "MarketingLead_Assignees" CASCADE;
DROP TABLE IF EXISTS "NaverPlaceKeywords" CASCADE;
DROP TABLE IF EXISTS "Ads_Group" CASCADE;
DROP TABLE IF EXISTS "Charges" CASCADE;
DROP TABLE IF EXISTS "CampaignKeywords" CASCADE;
DROP TABLE IF EXISTS "Propositions" CASCADE;
DROP TABLE IF EXISTS "Keywords" CASCADE;
DROP TABLE IF EXISTS "Companies" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "Ads_Local" CASCADE;

-- =====================================================
-- 시퀀스 삭제 (PostgreSQL용)
-- =====================================================

DROP SEQUENCE IF EXISTS "Companies_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Keywords_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Propositions_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "CampaignKeywords_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Charges_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "NaverPlaceKeywords_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "MarketingLead_Assignees_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Ads_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "AdKeywords_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "AdNaverPlaceKeywords_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "AuthUsers_Card_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "App_Inquiry_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "App_Inquiry_Answer_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "App_Inquiry_Answer_AutoGenerated_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "MarketingLead_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Packages_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Packages_Log_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "PremiumPackages_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "SumemPoints_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "Ads_Termination_Log_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "AdKeywordRankHistories_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "KeywordRankHistories_id_seq" CASCADE;
DROP SEQUENCE IF EXISTS "NaverPlaceKeywordRankHistories_id_seq" CASCADE;

-- =====================================================
-- 뷰 삭제 (있다면)
-- =====================================================

DROP VIEW IF EXISTS "workflow_summary" CASCADE;
DROP VIEW IF EXISTS "message_statistics" CASCADE;
DROP VIEW IF EXISTS "template_usage_summary" CASCADE;

-- =====================================================
-- 함수 삭제 (있다면)
-- =====================================================

DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;
DROP FUNCTION IF EXISTS update_daily_statistics() CASCADE;

-- =====================================================
-- 외래키 제약조건 재활성화
-- =====================================================

-- MySQL용
-- SET FOREIGN_KEY_CHECKS = 1;

-- PostgreSQL용
-- SET session_replication_role = DEFAULT;

-- =====================================================
-- 삭제 확인
-- =====================================================

-- 남은 테이블 확인
SELECT tablename 
FROM pg_tables 
WHERE schemaname = 'public' 
ORDER BY tablename;

-- 남은 시퀀스 확인
SELECT sequencename 
FROM pg_sequences 
WHERE schemaname = 'public' 
ORDER BY sequencename; 