-- =====================================================
-- Supabase SQL Editor 단계별 테이블 삭제 명령어
-- 복사해서 하나씩 실행하세요
-- =====================================================

-- 1단계: 기존 하이브리드 시스템 테이블 삭제 (있다면)
DROP TABLE IF EXISTS workflow_runs CASCADE;
DROP TABLE IF EXISTS workflows CASCADE;
DROP TABLE IF EXISTS template_usage_logs CASCADE;
DROP TABLE IF EXISTS message_templates CASCADE;
DROP TABLE IF EXISTS message_logs CASCADE;
DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS api_credentials CASCADE;
DROP TABLE IF EXISTS user_activity_logs CASCADE;
DROP TABLE IF EXISTS system_event_logs CASCADE;
DROP TABLE IF EXISTS daily_statistics CASCADE;
DROP TABLE IF EXISTS monthly_statistics CASCADE;

-- 2단계: 기존 MySQL 마이그레이션 테이블들 삭제 (1차)
DROP TABLE IF EXISTS "NaverPlaceKeywordRankHistories" CASCADE;
DROP TABLE IF EXISTS "KeywordRankHistories" CASCADE;
DROP TABLE IF EXISTS "AdKeywordRankHistories" CASCADE;
DROP TABLE IF EXISTS "Ads_Termination_Log" CASCADE;
DROP TABLE IF EXISTS "Ads_Payment" CASCADE;

-- 3단계: 기존 MySQL 마이그레이션 테이블들 삭제 (2차)
DROP TABLE IF EXISTS "SumemPoints" CASCADE;
DROP TABLE IF EXISTS "PremiumPackages" CASCADE;
DROP TABLE IF EXISTS "Packages_Log" CASCADE;
DROP TABLE IF EXISTS "Packages" CASCADE;
DROP TABLE IF EXISTS "MarketingLead" CASCADE;

-- 4단계: 기존 MySQL 마이그레이션 테이블들 삭제 (3차)
DROP TABLE IF EXISTS "App_Inquiry_Answer_AutoGenerated" CASCADE;
DROP TABLE IF EXISTS "App_Inquiry_Answer" CASCADE;
DROP TABLE IF EXISTS "App_Inquiry" CASCADE;
DROP TABLE IF EXISTS "AuthUsers_Card" CASCADE;
DROP TABLE IF EXISTS "Channels" CASCADE;

-- 5단계: 기존 MySQL 마이그레이션 테이블들 삭제 (4차)
DROP TABLE IF EXISTS "Contracts" CASCADE;
DROP TABLE IF EXISTS "AdNaverPlaceKeywords" CASCADE;
DROP TABLE IF EXISTS "Ads_Keyword" CASCADE;
DROP TABLE IF EXISTS "AdKeywords" CASCADE;
DROP TABLE IF EXISTS "Ads" CASCADE;

-- 6단계: 기존 MySQL 마이그레이션 테이블들 삭제 (5차)
DROP TABLE IF EXISTS "MarketingLead_Assignees" CASCADE;
DROP TABLE IF EXISTS "NaverPlaceKeywords" CASCADE;
DROP TABLE IF EXISTS "Ads_Group" CASCADE;
DROP TABLE IF EXISTS "Charges" CASCADE;
DROP TABLE IF EXISTS "CampaignKeywords" CASCADE;

-- 7단계: 기존 MySQL 마이그레이션 테이블들 삭제 (최종)
DROP TABLE IF EXISTS "Propositions" CASCADE;
DROP TABLE IF EXISTS "Keywords" CASCADE;
DROP TABLE IF EXISTS "Companies" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "Ads_Local" CASCADE;

-- 8단계: 뷰 삭제
DROP VIEW IF EXISTS "workflow_summary" CASCADE;
DROP VIEW IF EXISTS "message_statistics" CASCADE;
DROP VIEW IF EXISTS "template_usage_summary" CASCADE;

-- 9단계: 함수 삭제
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;
DROP FUNCTION IF EXISTS update_daily_statistics() CASCADE;

-- 10단계: 확장 기능 정리 (선택사항)
-- DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;
-- DROP EXTENSION IF EXISTS "pg_stat_statements" CASCADE;

-- 11단계: 삭제 확인
SELECT 
    'Tables remaining:' as info,
    COUNT(*) as count
FROM pg_tables 
WHERE schemaname = 'public';

-- 12단계: 남은 테이블 목록 확인
SELECT 
    tablename,
    tableowner
FROM pg_tables 
WHERE schemaname = 'public' 
ORDER BY tablename; 